### ISSUE TITLE
Issue with createTheme on MUI

### ISSUE THREAD

**Issue by erik-lance** [erik-lance/portfolio-website#1]
Having errors at layout.tsx as I can't seem to use my theme and themeprovider wrapper over it. Error is:
```
> portfolio-website@0.1.0 build
> next build

- info Creating an optimized production build
- info Compiled successfully
- info Linting and checking validity of types
- info Collecting page data ...Error: Attempted to call createTheme() from the server but createTheme is on the client. It's not possible to invoke a client function from the server, it can only be rendered as a Component or passed to props of a Client Component.
    at Object.defineProperties.$$typeof.value (D:\Code\_github\portfolio-website\.next\server\chunks\367.js:71931:23)
    at 59210 (D:\Code\_github\portfolio-website\.next\server\app\page.js:403:37)
    at Function.__webpack_require__ (D:\Code\_github\portfolio-website\.next\server\webpack-runtime.js:25:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async collectGenerateParams (D:\Code\_github\portfolio-website\node_modules\next\dist\build\utils.js:826:17)

> Build error occurred
Error: Failed to collect page data for /
    at D:\Code\_github\portfolio-website\node_modules\next\dist\build\utils.js:1156:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
```

**Comment by GeorgesLevyEtoundi** [comment]
Hello. I'm facing the same issue with my app. I want to deploy on vercel, and when building the project I encountered and error saying that my layout.jsx should be a server component. But my layout.jsx is wrapped with themeprovider and theme MUI components. How did you solve your issue?

**Comment by erik-lance** [comment]
Hello @GeorgesLevyEtoundi ! I had a friend help me fix this issue! It's under commit d96af1f by @ubergonmx :) 

I initially had my ThemeProvider wrapping my layout file too, but @ubergonmx fixed it by creating an entirely new component called `ThemeWrapper` that acts as a `ThemeProvider` . He also added `'use client'` at the start of the new `ThemeWrapper` component he added.

**Comment by aar0npal** [comment]
> Hello. I'm facing the same issue with my app. I want to deploy on vercel, and when building the project I encountered and error saying that my layout.jsx should be a server component. But my layout.jsx is wrapped with themeprovider and theme MUI components. How did you solve your issue?

Based on [Next.js documentaton](https://nextjs.org/docs/getting-started/react-essentials#moving-client-components-to-the-leaves:~:text=Instead%20of%20making,to%20the%20client.), I moved the component to the leaves. This is to avoid poisoning `layout.tsx` which is a server component. I learned this as well from this [YouTube video](https://www.youtube.com/watch?v=BZlwtR9pDp4).

**Comment by GeorgesLevyEtoundi** [comment]
Guys thank you so much... I'm gonna implement this and make you guys some feedback.

**Comment by GeorgesLevyEtoundi** [comment]
It WORKED LIKE A CHARM. 

Thanks a bunch guys, can't say thank you enough.

**Comment by erik-lance** [comment]
Glad to hear it worked out for you! Good luck with your project!:)
